### PR TITLE
PWA install compatibility

### PR DESCRIPTION
**Pull request by glitch128**
# Pull Request Template

## Description

This allows the web editor to be installed as a PWA. what I added was a manifest link to the index.html file, a manifest.json file, two(2) .ico files and one(1) PNG file in a new "icons" folder

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
I used GitHub pages to test the changes, and used developer tools to identify any errors

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by glitch128** [comment]
Ok, I forgot to change the start_url to "/editor/index.html"
fixed now.

**Comment by glitch128** [comment]
I changed the manifest description to "Web powered cross-platform 3D, WebXR game engine"

**Comment by tentone** [comment]
Thanks a lot for this contribution. LGTM. 

Merged!

**Comment by glitch128** [comment]
hey, I just installed the PWA, but it shows up like this on chromeOS
image
i tested changing the "property" attribute for the icons on replit, and the only way for it to work while also showing the "install" prompt is setting it to "any maskable", and it shows up like this
image
 but I hear that doing this isn't recommended. Is it ok if I make it "any maskable"?
also, here is the link to the repl
[https://nunustudio.glitch128.repl.co/docs/editor/index.html](https://nunustudio.glitch128.repl.co/docs/editor/index.html)

**Pull request merged**
