### PR TITLE
Hello Tentone

### PR DESCRIPTION
**Pull request by Seagat2011**
I wish to contribute with you. The first thing I needed to do is get my editor working without node.js installed. So I duplicated directories after pulling in most of your updates. 

#### Revisions:

1. I moved the include(..) calls in Editor.js into editor.html
2. I added your favicons
3. I revised FileSystem.js to use (mostly) asynchronous calls as well as callbacks to load font, textures, and audio into the browser; however, the "if FileSystem.fs" portions are untested (sorry)

#### Notes:
1. I'm working on a visual classBuilder tool to make coding faster ..
2. Projects worked on in the browser can also be exported (using Save/SaveAs) to DOWNLOADS folder and also Loaded from the DEFAULT/SOURCE/PROJECTS subdirectory

### CODE REVIEW

**Comment by tentone** [comment]
Hi, thanks a lot, currently i'm focused on finishing documentation for the editor and figuring out how to fix some bugs (specially ones related with NWJS).

As soon as i get this done i will come back here to check your changes carefully!

For the beta version i do intend to keep the editor nwjs only and use node.js for file and OS tasks, but i also plan to have a fully node.js free version available after that so that people can use it in the same way the theejs editor is used currently!

Once again thanks a lot!

**Comment by tentone** [comment]
@Seagat2011 

I have now seen your code, tomorrow i will take time to start merging your code with the repository in its current state, after im done i come back here to show you how it is.

I removed yesterday some leftover dependencies from the UI .I think this will be ready on time for the beta release (i'm trying to do it before 17 feb)

Once again thanks a lot for your time. You done pretty much everything that is needed to run it inside the browser without node.

**Comment by tentone** [comment]
Im currently working on this, im trying to merge everything into a single code base, there are still some problems.

I have to figure out a better way to load all .css styles for the codemirror themes, (without requiring building everything)

For file reading/writing i also have to find a good way to write and download binary files, to export images and videos from the editor.

**Comment by tentone** [comment]
@Seagat2011 Hi there

I merged today these changes you have proposed, i hope i havent missed anything, the standalone version is available at http://nunustudio.org/editor/editor.html

Once again thanks a lot 👍

**Comment by weekendkoder** [comment]
One thing i have to mention to a "online editor".

You are not allways "online". Sometimes you are disconnected etc. I guess, once loaded, everything is in your cache of the browser. But sometimes it happens, that your browser crashes. This means, if you are online, and everything is loaded, but it crashes and your i-net connection is lost, you don´t have any possibility to work with nunuStudio.

Therefore i would say, a NWJS, a local "offline" version is really important ! My 2 cent.

**Comment by tentone** [comment]
@weekendkoder There is already a offline and online version available.

Please check the project website.

**Pull request closed without merging**
